/*
 * This source file was generated by the Gradle 'init' task
 */
package lab4;

import lab4.Cartas.CartaCura;
import lab4.Cartas.CartaMortalForca;
import lab4.Cartas.CartaVelocidade;
import lab4.Efeitos.Forca;
import lab4.Entidades.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void testCartaMortalForca() { /*testando cartas novas*/
        Heroi heroi = new Heroi("Arthur", 40, 0, 10);
        heroi.aplicarEfeito(new Forca("Força explosiva", heroi, 1));
        // Verifica se os atributos foram atribuídos corretamente
        CartaMortalForca mortalForca = new CartaMortalForca("", "causa (9 vezes força do alvo) de dano e gasta todo o acúmulo de força do alvo / custa 3 de energia", 3);
        
        mortalForca.usar(heroi);
        assertNull(heroi.getForca());
        assertEquals(31, heroi.getVida());
    }
    @Test
    void testCura() { /*testando cartas novas*/
        Heroi heroi = new Heroi("Arthur", 40, 5, 10);
        heroi.receberDano(2);
        // Verifica se os atributos foram atribuídos corretamente
        CartaCura pocao = new CartaCura("poção de cura", "concede 5 de cura / custa 1 energia", 1);
        pocao.usar(heroi);
        assertEquals(40, heroi.getVida());
    }
    @Test
    void testVelocidade() { /*testando cartas novas*/
        Heroi heroi = new Heroi("Arthur", 40, 5, 10);
        // Verifica se os atributos foram atribuídos corretamente
        CartaVelocidade agilidade = new CartaVelocidade("pés ágeis", "concede +2 de velocidade ao alvo / custa 1 energia", 1);

        agilidade.usar(heroi);
        assertEquals(12, heroi.getVelocidade());
    }
}